CC=g++

OPENGLLIB= -lGL
GLEWLIB= -lGLEW
GLFWLIB = -lglfw
LIBS=$(OPENGLLIB) $(GLEWLIB) $(GLFWLIB)
LDFLAGS=-L/usr/local/lib 
CPPFLAGS=-I/usr/local/include -I./

BIN=a1model
SRCS=a1model.cpp gl_framework.cpp shader_util.cpp cube.cpp grid.cpp voxelized_grid.cpp 
INCLUDES=gl_framework.hpp shader_util.hpp model_helper.hpp cube.hpp grid.hpp voxelized_grid.hpp

all: $(BIN)

$(BIN): $(SRCS) $(INCLUDES)
	g++ $(CPPFLAGS) $(SRCS) -o $(BIN) $(LDFLAGS) $(LIBS)

clean:
	rm -f *~ *.o $(BIN)
